import {GulpTask, IBuildConfig} from '@microsoft/gulp-core-build';
import * as ncc from '@zeit/ncc';
import * as fs from 'fs';
import * as path from 'path';

/**
 * @public
 */
export interface INccOptions {
  cache?: string | boolean;
  externals?: string[];
  filterAssetBase?: string;
  minify?: boolean;
  sourceMap?: boolean;
  sourceMapBasePrefix?: string;
  sourceMapRegister?: boolean;
  v8cache?: boolean;
}

/**
 * @public
 */
export interface INccTaskConfig {
  /**
   * ncc config object.
   */
  config?: INccOptions;

  /**
   * Input file to pass to ncc for compilation.
   */
  inputFile?: string;

  /**
   * Output file to write the compiled output generated by ncc to.
   */
  outputFile?: string;
}

/**
 * @public
 */
export class NccTask extends GulpTask<INccTaskConfig> {
  constructor() {
    super(
      'ncc',
      {
        inputFile: './src/index.ts',
        outputFile: './dist/index.js'
      }
    );
  }

  public async executeTask(): Promise<void> {
    const output: Output = await ncc(this.taskConfig.inputFile, {
      ...this.taskConfig.config,
      quiet: true
    });

    const outputPath: string = this.resolvePath(this.taskConfig.outputFile || './dist/index.js');

    outputPath.split(path.sep).reduce((previousValue, currentValue) => {
      if (!fs.existsSync(previousValue)) {
        fs.mkdirSync(previousValue);
      }

      return path.join(previousValue, currentValue);
    });

    if (!!output.code) {
      await new Promise((resolve, reject) => {
        fs.writeFile(
          outputPath,
          output.code,
          'utf8',
          (err) => err ? reject(err) : resolve()
        );
      });
    }

    if (!!output.map) {
      await new Promise((resolve, reject) => {
        fs.writeFile(
          `${outputPath}.map`,
          output.map,
          'utf8',
          (err) => err ? reject(err) : resolve()
        );
      });
    }
  }

  public isEnabled(buildConfig: IBuildConfig): boolean {
    return super.isEnabled(buildConfig) && !!this.taskConfig.inputFile && !!this.taskConfig.outputFile;
  }
}

/**
 * @private
 */
type Output = {
  code: string,
  map: string
};
